### ISSUE TITLE
Change of Release Branch Naming Required?

### ISSUE THREAD

**Issue by georg-jung** [Technion236503/2020b-Haifa3D#10]
Hey @mikimn,

I already started semi-automatic versioning before reading the sprint 1 doc. That's why my v1.0 release branch is called `release/v1.0` now, not `release/1.0`. I liked that scheme because it's more in line with the default tagging of GitHub releases on one hand and the defaults of my versioning solution [NBGV](https://github.com/dotnet/Nerdbank.GitVersioning) on the other hand. I did notice it is different from Git Flow and your requirement, which, I have to admit, is printed bold and quite dominant in the task PDF.

I still think it's cleaner to leave the naming with `v` - so if you think I should change the naming scheme just drop a short `Yes` comment please :-).

Should I rename?

**Comment by mikimn** [comment]
No need to change, you are exempt from that "strict" requirement of the submission ;)
