### ISSUE TITLE
Sprint 1 Status Review

### ISSUE THREAD

**Issue by georg-jung** [Technion236503/2020b-Haifa3D#11]
I managed to implement most stuff I had planned for sprint 1. I think the app is now in a state that obviously is not finished and fine-tuned but it is quite usable and offers most of the hands features on the phone. In this issue I'll just detail what has changed, not what I feel went as originally planned.

* I discussed the protocol again with Shunit and we added a central feature:
  * Every action can not just contain one movement (i.e. open all fingers) but *n* movements (i.e. open all fingers until open; then close for 50ms)
  * This gives us quite much more flexibility and even simplifies the protocol at the same time (otherwise we would have needed more "motor directions" that don't feel natural at this point)
  * Corresponding up-to-date documentation is available [here](https://github.com/Technion236503/2020b-Haifa3D/blob/master/Protocol.md).
* I decided to drop `As a developer, I want to see some diagnostic data about the communication and the hand controller in the app to support me while debugging etc..`
  * I just never had the feeling that I'd need this feature in app; the debugger in android studio is probably much more powerful for the use cases that are currently relevant than anything I could implement
  * I thought it's pointless to implement a development feature if even I wouldn't use it myself so I decided to drop this and focus on more user visible things
* `As a project stakeholder, I care about the user's need for privacy.` is neither done nor not done. Until now there just wasn't anything where I had the feeling it would be relevant to privacy.
* `As a user, I want to freely configure presets that define a specific state of my hand such as a gesture.` due to the changes I detailed above, one more level is required here: `(n Presets) --Edit--> (n Movements) --Edit--> (Movement Details)`
  * currently, editing of movement details is still missing
  * still thats kind of in line with what I planned to implement for sprint 1, as there's one more level now
* `As a user, I want to see status information about my hand such as battery percentage.`
  * My status fragment is still the same one as it was the last time we met (so: quite basic)
  * I did many steps in the background and defined the configuration [protocol](https://github.com/Technion236503/2020b-Haifa3D/blob/master/Protocol.md) etc., but some final UI steps are still missing

All in all I think I made good progress and I hope the current state of development can be of direct use to Shunit soon. I implemented a bit more than planned on the protocol / multi movement side and in return postponed the configuration screen a bit, but still layed some relevant foundation for that.

I added some screenshots to the readme and to some other issues, so that it's easier to understand where we currently are, I guess. The current build of `release/v1.0` is available [here](https://github.com/georg-jung/technion-robotic-arm/releases/tag/v1.0.2).

I'm a bit late regarding the non-code & non-binary deliverables such as the programmer's handbook. I'll provide you with it tomorrow, I hope that's not a too big issue.

For when should we plan the next meeting? I'm rather flexible, just suggest something. Is there anything more I should look into before that date (except from the things mentioned in the sprint 1 pdf)?

**Comment by mikimn** [comment]
Looks good, we will schedule a meeting for a live demo and prospect, hopefull with Shunit, sometime this week.

The Sprint1 submission is extended due today (1.6) so make sure you at least submit an APK deliverable to the course website, as for other deliverables - try and complete them this week, and if you see that you don't make it in time, give me a shoutout here
