### ISSUE TITLE
PlayStore Upload

### ISSUE THREAD

**Issue by georg-jung** [Technion236503/2020b-Haifa3D#13]
I know the deadline already passed quite some time ago. I did not work on the upload for now as things like the name of the app are still not final (I think Shunit still needs to discuss that with someone) and it'd probably be better if they were before.

I already have a paid developer account, so I don't need one.

**Comment by mikimn** [comment]
You may upload the app to your own account, and try to have it there by the time we schedule a meeting. I will notify you when I am available

**Comment by mikimn** [comment]
For Sprint1 you may upload the app under the name "Haifa3D" (you can always change the app's display name later on)

**Comment by georg-jung** [comment]
Okay, I submitted the current version to the play store. I sent an invitation to your gmail so that you have access to this app on my account too.

**Comment by georg-jung** [comment]
Additionally, I improved the CI/CD process. The aab is now signed in CI (using a keystore from a secure file and corresponding secrets variables). I could add someone else to my Azure DevOps project or maybe create a Haifa3d Azure DevOps organization. That would lift the dependency on me for the keystore etc. while still beeing as secure as it gets. The signed aab and the unsigned debug apk are automatically pushed to my GitHub releases from `release/v` branches (still my github releases as I don't have the permission to allow azure devops access to the shared project). (Actually, the signed ones are just created for release branches; otherwise there would be a vulnerability when someone PRs).

The android versionCode is now automatically generated by counting the commits from the initial commit till the ref the build is based on (that's not really perfect but good enough for now I guess). Thus, the release process is now almost completely automated. When someone (and this explicitly does not have to be me) commits, an APK & AAB get publicly available automatically. When someone commits to `release/v` the same + a upload-key-signed AAB get published automatically. Publishing to Play Store just requires uploading there, no more other tooling needed.

**Comment by georg-jung** [comment]
App is now published in Play Store (but not publicly listed). I added your & Shunit's gmail to the list of testers @mikimn. Link is https://play.google.com/apps/internaltest/4698438320320970848.
